"""Render the BOM master data to the docs page and procurement CSV.

Both outputs are committed (like the 3D viewer GLBs) so the website and
GitHub browsers always have them; `python -m quiver.bom render --check`
fails CI when they are stale. Output is deterministic: items in file
order, LF endings, trailing newline.
"""

import csv
import io

from quiver.bom import REPO_ROOT, Bom

DOCS_MD = REPO_ROOT / "docs" / "Manufacturing" / "BOM.md"
DOCS_CSV = REPO_ROOT / "docs" / "Manufacturing" / "quiver-bom.csv"

_GITHUB_BLOB = "https://github.com/Arrow-air/project-quiver/blob/main/"

_CSV_COLUMNS = [
    "id", "name", "category", "qty_vehicle", "qty_order", "sourcing",
    "material", "spec", "supplier", "supplier_part_number", "supplier_url",
    "unit_cost_usd", "order_cost_usd", "order_details", "notes",
]


def _order_qty(item) -> int | str:
    if item.included_in:
        return 0
    if item.purchase_qty is not None:
        return item.purchase_qty
    return item.qty


def _order_cost(item) -> float | None:
    qty = _order_qty(item)
    if item.unit_cost_usd is None or not isinstance(qty, int):
        return None
    return round(item.unit_cost_usd * qty, 2)


def render_csv(bom: Bom) -> str:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=_CSV_COLUMNS, lineterminator="\n")
    writer.writeheader()
    for cat in bom.categories:
        for item in cat.items:
            preferred = item.suppliers[0] if item.suppliers else None
            order_details = item.purchase_note or ""
            if item.included_in:
                order_details = f"included with {item.included_in}"
            order_cost = _order_cost(item)
            writer.writerow({
                "id": item.id,
                "name": item.name,
                "category": cat.name,
                "qty_vehicle": item.qty,
                "qty_order": _order_qty(item),
                "sourcing": item.sourcing,
                "material": item.material or "",
                "spec": item.spec or "",
                "supplier": preferred.name if preferred else "",
                "supplier_part_number": (preferred.part_number or "") if preferred else "",
                "supplier_url": (preferred.url or "") if preferred else "",
                "unit_cost_usd": f"{item.unit_cost_usd:.2f}" if item.unit_cost_usd is not None else "",
                "order_cost_usd": f"{order_cost:.2f}" if order_cost is not None else "",
                "order_details": order_details,
                "notes": item.notes or "",
            })
    return buf.getvalue()


def _supplier_cell(item) -> str:
    if item.included_in:
        return f"included with {item.included_in}"
    parts = []
    for s in item.suppliers:
        label = s.name
        if s.part_number:
            label += f" {s.part_number}"
        parts.append(f"[{label}]({s.url})" if s.url else label)
    return "; ".join(parts)


def _design_cell(item) -> str:
    if not item.design_ref:
        return ""
    return f"[design]({_GITHUB_BLOB}{item.design_ref})"


def render_markdown(bom: Bom) -> str:
    meta = bom.meta
    total = sum(c for c in (_order_cost(i) for i in bom.items()) if c is not None)

    lines = [
        "---",
        "title: Bill of Materials",
        "sidebar_label: Bill of Materials",
        "description: Quality reference BOM for the Quiver Dev-Kit",
        "---",
        "",
        "<!-- Generated by `python -m quiver.bom render` from bom/*.yaml. Do not edit by hand. -->",
        "",
        "# Bill of Materials",
        "",
        f"**Revision {meta['revision']}"
        + (" (draft)" if meta.get("status") == "draft" else "")
        + f"** — {meta['config']} configuration — {meta['date']}",
        "",
        "This page is generated from the version-controlled BOM master data in",
        "[`bom/`](https://github.com/Arrow-air/project-quiver/tree/main/bom).",
        "Manufacturers building for customer orders must build against a",
        "declared revision of this document.",
        "",
        "**Download:** [procurement CSV](./quiver-bom.csv) — one row per line",
        "item with order quantities, supplier links, and indicative costs.",
        "",
        f"Indicative build cost: **${total:,.2f}** (component prices as of",
        f"{meta.get('cost_as_of', meta['date'])}; verify with suppliers before ordering).",
        "",
    ]

    for cat in bom.categories:
        lines += [f"## {cat.name}", ""]
        lines.append("| ID | Part | Qty | Sourcing | Material / Spec | Supplier | Unit cost | Design |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for item in cat.items:
            mat = " — ".join(x for x in (item.material, item.spec) if x)
            cost = f"${item.unit_cost_usd:.2f}" if item.unit_cost_usd is not None else ""
            qty = str(item.qty)
            if item.purchase_qty is not None and item.purchase_qty != item.qty:
                qty += f" (order {item.purchase_qty})"
            lines.append(
                f"| {item.id} | {item.name} | {qty} | {item.sourcing} | {mat} "
                f"| {_supplier_cell(item)} | {cost} | {_design_cell(item)} |"
            )
        lines.append("")

    lines += [
        "## Notes",
        "",
        "- Quantities are per vehicle; \"order\" quantities reflect stock sizes",
        "  or batch minimums (full detail in the CSV).",
        "- `AR` = as required (consumables and tools).",
        "- PCB component-level BOMs are KiCad production exports under",
        "  [`src/pcb/`](https://github.com/Arrow-air/project-quiver/tree/main/src/pcb)",
        "  — each board appears here as a single assembled item.",
        "- Items whose notes say `TBC` are unconfirmed while this revision is",
        "  a draft; see [`bom/README.md`](https://github.com/Arrow-air/project-quiver/blob/main/bom/README.md)",
        "  for the revision policy.",
        "",
    ]
    return "\n".join(lines)


def render(bom: Bom) -> dict:
    """Return {path: content} for all generated outputs."""
    return {DOCS_MD: render_markdown(bom), DOCS_CSV: render_csv(bom)}
