name: BOM

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  generated-docs:
    name: Generated BOM docs are current
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python tools/bom/generate_bom_docs.py --check
